name: CI Mi Biblioteca

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  build-test:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x


    - name: Restore dependencies
      run: dotnet restore MiBiblioteca.Tests/MiBiblioteca.Tests.csproj


    - name: Build
      run: dotnet build MiBiblioteca.Tests/MiBiblioteca.Tests.csproj --no-restore


    - name: Run tests
      run: dotnet test MiBiblioteca.Tests/MiBiblioteca.Tests.csproj --no-build